import { Sen } from "next/font/google";
import "./globals.css";
import LayoutProvider from "./components/providers/LayoutProvider";
import ProtectedRoute from "./store/ProtectedRoutes";

const senFont = Sen({
  variable: "--font-sen",
  subsets: ["latin"],
  weight:['800']
});

export const metadata = {
  title: "Intranet",
  icons:{
    icon: "/images/remove.png",
    shortcut: "/images/remove.png",
  },
  description: "Generated by create next app",
};
export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={` ${senFont.variable}`}>
        <ProtectedRoute>
            <LayoutProvider>
                {children}
            </LayoutProvider>
        </ProtectedRoute>
      </body>
    </html>
  );
}
