import { Sen } from "next/font/google";
import "./globals.css";
import LayoutProvider from "./components/providers/LayoutProvider";

const senFont = Sen({
  variable: "--font-sen",
  subsets: ["latin"],
  weight:['800']
});

export const metadata = {
  title: "Intranet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${senFont.variable}`}
>
        <LayoutProvider>{children}</LayoutProvider>
      </body>
    </html>
  );
}
